[workspace]
authors = ["Jason C. Klima"]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "pyrosettacluster-example-1"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
matplotlib = "*"
pyrosetta = "2026.*"
python = "3.14.*"

[pypi-dependencies]
pyrosetta-distributed = ">=0.0.4"
