[workspace]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "PyRosettaCluster Pixi Project"
version = "1.0.0"

[dependencies]
python = "==3.14"
pyrosetta = ">=2026.3"

[pypi-dependencies]
pyrosetta-distributed = ">=0.0.4"
