[workspace]
authors = ["Jason C. Klima"]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "pyrosettacluster-pixi-project"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
python = "3.14.*"
pyrosetta = ">=2026.03,<2027"

[pypi-dependencies]
pyrosetta-distributed = ">=0.0.4"
