[workspace]
authors = ["Jason C. Klima"]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "pyrosettacluster-example-2"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
pyrosetta = "2026.*"
python = "3.13.*"

[pypi-dependencies]
matplotlib = "*"
pyrosetta-distributed = ">=0.0.4"
rc-foundry = { version = ">=0.1.9", extras = ["all"] }
seaborn = "*"
