[workspace]
authors = ["Jason C. Klima"]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "pyrosettacluster-example-2"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
python = "3.12.*"

[pypi-dependencies]
matplotlib = ">=3.10.8"
pyrosetta = ">=2026.3"
pyrosetta-distributed = ">=0.0.4"
rc-foundry = { version = ">=0.1.9", extras = ["all"] }
seaborn = ">=0.13.2"

[pypi-options]
find-links = [{url = "https://west.rosettacommons.org/pyrosetta/quarterly/release.cxx11thread.serialization/"}]
