[workspace]
authors = ["Jason C. Klima"]
channels = ["https://conda.rosettacommons.org", "conda-forge"]
name = "pyrosettacluster-example-2"
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
python = "3.12.*"
pyrosetta = { version = ">=2026.3", channel = "https://conda.rosettacommons.org" }

[pypi-dependencies]
matplotlib = "*"
pyrosetta-distributed = ">=0.0.4"
rc-foundry = { version = ">=0.1.9", extras = ["all"] }
seaborn = "*"
